# Generated by Django 5.1 on 2024-09-06 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 11, 25, 59, 602681, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='frequency',
            field=models.CharField(default='one-time', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 11, 27, 36, 580023, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
