# Generated by Django 5.1 on 2024-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_end_date_note_frequency_note_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateField(),
        ),
    ]
